version: "3.8"
services:
    web:
        build: .
        command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./app:/app
        ports: 
            - "8000:8000"
    mongo:
        image: "mongo:3-xenial"
        restart: always
        ports: 
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        